#- id: detect_presence_change
#  alias: Detect Change of Presence
#  trigger:
#  - entity_id: device_tracker.404e36834b54,device_tracker.68ef4339078e,device_tracker.6c4d7365ea91,device_tracker.c0eefbf5049c
#    platform: state
#  condition:
#  - after: 08:00:00
#    before: 00:00:00
#    condition: time
#  action:
#    service: script.turn_on
#    entity_id: script.notify_change_presence
#    data_template:
#      variables:
#        to_state: >
#          {{trigger.to_state.state}}
#        friendly_name: >
#          {{trigger.to_state.attributes.friendly_name}}
#  initial_state: false
#  hide_entity: true

#- id: keep_electric_blanket_warm
#  alias: Keep Electric Blanket Warm
#  trigger:
#    platform: time
#    minutes: '51'
#    seconds: '00'
#  action:
#    - service: switch.turn_off
#      entity_id: switch.jerry_lamp
#    - delay: 00:00:05
#    - service: switch.turn_on
#      entity_id: switch.jerry_lamp

- id: bedtime
  alias: Bedtime Lights
  trigger:
    platform: time
    at: '23:30:00'
  condition:
    - condition: state
      entity_id: 'person.jerry_2'
      state: 'home'
    - condition: time
      weekday:
        - sun
        - mon
        - tue
        - wed
        - thu
  action:
    - service: light.turn_off
      data:
        entity_id: light.jerry_s_floor_lamp
    - service: light.turn_on
      data:
        entity_id: light.jerry_color
        brightness_pct: 100
        rgb_color: [255, 0, 0]
    - service: light.turn_on
      data:
        entity_id: light.jerry_bedside
        brightness_pct: 5
        kelvin: 2200

- id: jerryleft
  alias: Jerry Away
  trigger:
    - platform: state
      entity_id: person.jerry_2
      from: 'home'
    - platform: zone
      entity_id: person.jerry_2
      zone: zone.Home
      event: leave
  action:
    - service: script.turn_on
      entity_id: script.turn_off_all_jerrys_lights
    - service: switch.turn_off
      entity_id: switch.jerrys_switch

- id: autorestart
  alias: Automatic Reboot
  trigger:
    - platform: time
      at: "04:00:00"
  action:
    - service: homeassistant.restart

- id: manual_flux
  alias: Manual Flux
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      above: 6
    - platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: 6
    - platform: time
      at: '22:00:00'
    - platform: time
      at: '5:00:00'
    - platform: state
      entity_id: light.jerry_s_bathroom_lights, light.jerry_bedside, light.jerry_s_floor_lamp
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: 'person.jerry_2'
      state: 'home'
  action:
    - service: python_script.manual_flux
