- id: bedtime
  alias: Bedtime Lights
  trigger:
  - at: '21:30:00'
    platform: time
  condition:
  - condition: time
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
  action:
  - data:
      entity_id:
        - switch.espresso_machine
        - switch.family_room_lamp
        - switch.plant_light
    service: switch.turn_off
  - data:
      entity_id:
        - light.dining_area_lights
        - light.office_lights
        - light.family_room_lights
        - light.breakfast_area_lights
    service: light.turn_off
  - delay: 00:00:01
  - service: light.turn_on
    data:
      entity_id: light.bedroom_lamp
#   - service: light.turn_on
#     data:
#       brightness_pct: 5
#       entity_id: light.color_1
#       rgb_color:
#       - 255
#       - 0
#       - 0
  - data: {}
    entity_id: script.1581047036822
    service: script.turn_on
- id: wakeup
  alias: Wakeup Lights
  trigger:
    platform: time
    at: 06:01:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: automation.turn_off
    entity_id: automation.manual_flux
  - delay: 00:00:01
  - service: python_script.manual_flux
    data:
      light: light.bedroom_1
      brightness_pct: 5
  - service: python_script.manual_flux
    data:
      light: light.bedroom_2
      brightness_pct: 25
#   - service: python_script.manual_flux
#     data:
#       light: light.color_1
#       brightness_pct: 100
  - delay: 00:01:00
  - service: python_script.fade_light
    data:
      entity_id: light.bedroom_lamp
      transition: 600
      brightness_pct: 100
  - delay: 00:00:03
  - service: automation.turn_on
    entity_id: automation.manual_flux
- id: fake_home
  alias: Fake at Home
  trigger:
  - platform: state
    entity_id: person.jerry_lin
    from: home
  - platform: zone
    entity_id: person.jerry_lin
    zone: zone.Home
    event: leave
  - platform: time
    at: '9:00:00'
  - platform: time
    at: '22:30:00'
  action:
  - service: automation.turn_off
    entity_id: automation.leave_home
  - service: light.turn_off
    entity_id: group.all_lights
  - service: switch.turn_off
    entity_id: group.all_switches
- id: leave_home
  alias: Leave Home
  trigger:
  - platform: state
    entity_id: person.jerry_lin
    from: home
  - platform: zone
    entity_id: person.jerry_lin
    zone: zone.Home
    event: leave
  - platform: time
    at: '9:00:00'
  action:
  - service: light.turn_off
    entity_id: group.all_lights
  - service: switch.turn_off
    entity_id: group.all_switches
- id: autorestart
  alias: Automatic Reboot
  trigger:
  - platform: time
    at: 04:00:00
  - platform: time
    at: '16:00:00'
  action:
  - service: homeassistant.restart
- id: manual_flux
  alias: Manual Flux
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    above: -3
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: -3
  - platform: time
    at: '21:30:00'
  - platform: time
    at: '5:00:00'
  - platform: template
    value_template: '{{ states(''sensor.time'') == (state_attr(''input_datetime.daylight_start_override'',
      ''timestamp'') | int | timestamp_custom(''%H:%M'', False)) }}'
  - platform: template
    value_template: '{{ states(''sensor.time'') == (state_attr(''input_datetime.daylight_end_override'',
      ''timestamp'') | int | timestamp_custom(''%H:%M'', False)) }}'
  - platform: state
    entity_id:
        - light.office_lights
        - light.bedroom_lamp
        - light.dining_area_lights
        - light.family_room_lights
        - light.entryway_light
        - light.color_1
        - light.closet_light
    from: 'off'
    to: 'on'
  action:
  - service: python_script.manual_flux
    data_template:
      light: '{{ trigger.entity_id }}'
- id: plant_light_on
  alias: Plant Light On
  trigger:
  - platform: time
    at: '9:00:00'
  action:
  - service: switch.turn_on
    entity_id: switch.plant_light
- id: plant_light_off
  alias: Plant Light Off
  trigger:
  - platform: time
    at: '17:00:00'
  action:
  - service: switch.turn_off
    entity_id: switch.plant_light
- id: fold_full_power
  alias: Set Folding@Home to Full
  trigger:
  - platform: time
    at: '22:00:00'
  action:
  - service: hassio.addon_stdin
    data:
      addon: a0d7b954_ssh
      input: /root/config/scripts/folding_at_home.py --action unpause --power
        full
- id: fold_light_power
  alias: Set Folding@Home to Off
  trigger:
  - platform: time
    at: '8:00:00'
  action:
  - service: hassio.addon_stdin
    data:
      addon: a0d7b954_ssh
      input: /root/config/scripts/folding_at_home.py --action pause
- id: night_light
  alias: Night Light
  trigger:
  - platform: time
    at: '22:00:00'
  condition:
  - condition: time
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
  - condition: state
    entity_id: light.bedroom_lamp
    state: 'on'
  action:
  - service: python_script.night_light
- id: '1591577075422'
  alias: Dim Dining Area Lights
  description: ''
  trigger:
  - entity_id: media_player.lg_tv_2
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: light.dining_area_lights
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: media_player.lg_tv_2
    state: 'on'
  - after: '17:00'
    condition: time
  - condition: state
    entity_id: light.dining_area_lights
    state: 'on'
  action:
  - delay: 00:00:03
  - data:
      brightness_pct: 10
    entity_id: light.dining_area_lights
    service: light.turn_on
- id: warm_up_espresso_machine
  alias: Warm Up the Espresso Machine
  trigger:
    - platform: time
      at: '06:00:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: switch.turn_on
      entity_id: switch.espresso_machine
- id: turn_off_espresso_machine
  alias: Turn Off the Espresso Machine
  trigger:
    - platform: time
      at: '08:00:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: switch.turn_off
      entity_id: switch.espresso_machine
