homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret homeassistant_elevation
  # metric for Metric, imperial for Imperial
  unit_system: !secret homeassistant_unit_system
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret homeassistant_time_zone
  customize: !include customize.yaml

frontend:

config:

updater:
  include_used_components: true

discovery:

history:

logbook:

map:

sun:

system_health:

wake_on_lan:

mobile_app:

sensor:
  - platform: systemmonitor
    resources:
      - type: processor_use
      - type: load_5m
      - type: memory_use_percent
      - type: swap_use_percent
      - type: disk_use_percent
        arg: /
      - type: last_boot
  - platform: uptime
    name: Uptime
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time_iso'

wemo:
    static:
        - 192.168.1.128

cloud:

person:

python_script:

light:
  - platform: group
    name: Bedroom Lamp
    entities:
      - light.bedroom_1
      - light.bedroom_2
  - platform: group
    name: Breakfast Area Lights
    entities:
      - light.breakfast_area_1
      - light.breakfast_area_2
  - platform: group
    name: Dining Area Lights
    entities:
      - light.dining_area_1
      - light.dining_area_2
  - platform: group
    name: Family Room Lights
    entities:
      - light.family_room_1
      - light.family_room_2
  - platform: group
    name: Office Lights
    entities:
      - light.office_1
      - light.office_2
  - platform: group
    name: All Lights
    entities:
      - light.office_1
      - light.office_2
      - light.family_room_1
      - light.family_room_2
      - light.dining_area_1
      - light.dining_area_2
      - light.breakfast_area_1
      - light.breakfast_area_2
      - light.bedroom_1
      - light.bedroom_2

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  
# Text to speech
tts:
  - platform: google_translate

# Example configuration.yaml entry
input_datetime:
  daylight_start_override:
    name: Daylight Start Override
    has_date: false
    has_time: true
    initial: '7:00:00'
  daylight_end_override:
    name: Daylight End Override
    has_date: false
    has_time: true
    initial: '19:30:00'

# LG TV Configuration
webostv:
  - name: LG TV
    host: 192.168.1.186
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: "20:17:42:58:13:2A"
        
# Wake-on-Lan Switch for Media Server
switch:
  - platform: wake_on_lan
    name: "Media Server"
    mac: "d4:3d:7e:bd:f2:07"
    host: 192.168.1.91
    turn_off:
      service: hassio.addon_stdin
      data:
        addon: a0d7b954_ssh
        input: "ssh -i /root/.ssh/local_network jerry@192.168.1.91 sudo poweroff"

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
